version: "3.3"
services: 
  api-go:
    build:
      args: 
        WORK_DIR: /go/src/github.com/MydroX/api-go
    container_name: api-go
    depends_on: 
      - api-go-db
    ports:
      - 8080:8080
      - 80:3000
    volumes: 
      - ../.:/go/src/github.com/MydroX/api-go
    networks: 
      - api-go
  
  api-go-db:
    image: mariadb:10.6.4
    container_name: api-go-db
    # volumes: 
      # - db-data:/var/lib/mysql
      # - db-conf:/etc/mysql
    ports: 
      - 3306:3306
    networks: 
      - api-go

networks:
  api-go:
    external: true
  
# volumes:
  # db-data:
  # db-conf: